
stages:
  - run_notebook

run_notebook_job:
  image: python:3.11
  stage: run_notebook
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    # Exécute le notebook directement et enregistre le résultat
    - jupyter nbconvert --to notebook --execute Gestion_Parking.ipynb --output Resultat_Executé.ipynb
  artifacts:
    paths:
      - Resultat_Executé.ipynb
    expire_in: 1 week
  only:
    changes:
      - Gestion_Parking.ipynb
      - requirements.txt
